[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F103C8Tx --no-location --rtt-scan-memory"

[build]
target = "thumbv7m-none-eabi"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[env]
DEFMT_LOG = "info"
